# -*- coding: utf-8 -*-
"""COLLEGE QUERY CHAT BOT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z0yEaFlSdWh0l7tFjBU4rnqXRiZfEaRE

Title: COLLEGE QUERY CHAT BOT

Step 1: Define a dictionary of questions and answers
"""

faq = {
    "admission process": "You need to fill out the online application form and submit the required documents. Visit our website for more.",
    "fee structure": "The annual fee is around ₹1,20,000 including tuition and other charges.",
    "courses offered": "We offer B.Tech, M.Tech, BBA, MBA, BSc, and MSc programs.",
    "hostel facilities": "Yes, separate hostels for boys and girls with Wi-Fi, mess, and security are available.",
    "contact info": "You can reach us at +91-9876543210 or email info@college.edu",
    "placement": "We have a strong placement cell with companies like Infosys, TCS, Wipro visiting every year."
}

"""Step 2: Process user input"""

def get_response(user_query):
    user_query = user_query.lower()
    for key in faq:
        if key in user_query:
            return faq[key]
    return "I'm sorry, I couldn't find the answer to that. Please contact the college for more details."

"""def:
     It means “define a function.”

get_response:
    This is the name of the function. You can name functions anything you want.

(user_query):
   This is the input to the function.

for key in faq:
    This means “for each word (key) in the faq dictionary…”

Step 3: Start chatbot loop (interactive)
"""

def start_chat():
    print("Welcome to the College Query Chatbot!")
    print("Ask your question or type 'exit' to quit.\n")

    while True:
        query = input("You: ")
        if query.lower() == 'exit':
            print("Bot: Thank you for visiting. Goodbye!")
            break
        response = get_response(query)
        print("Bot:", response)

"""while loop:
     “Keep doing this action until I say stop.”

break:
      This stops the loop and ends the function.

Step 5: Run the chatbot
"""

start_chat()