# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19v_2kpzZ4KrYoOM2XXnh6grX6eE0DgeD
"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

vocab_size = 1000
embedding_dim = 64
max_length = 100

model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=embedding_dim),
    LSTM(units=64),
    Dense(units=1, activation='sigmoid')
])

model.compile(loss='binary_crossentropy',optimizer ='adam',metrics = ['accuracy'])

model.summary()